elevation_mapping:
  ros__parameters:
    # input_sources: ['lidar_boom'] # A name to identify the input source
    inputs: ['lidar_boom', 'lidar_front_left'] # A name to identify the input source
    lidar_boom:
      type: pointcloud # Supported types: pointcloud
      topic: /trimesh_self_filter/lidar_boom
      # topic: /livox/lidar_boom
      queue_size: 10
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
        type: laser
    lidar_front_left:
      type: pointcloud # Supported types: pointcloud
      topic: /trimesh_self_filter/lidar_front_left
      # topic: /livox/lidar_front_left
      queue_size: 10
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
        type: laser
    map_frame_id: "SHOVEL_elevation_map"
    robot_base_frame_id: "BASE"
    robot_pose_with_covariance_topic: "" # Leaving this empty skipps pose covariance updates.
    robot_pose_cache_size: 200
    track_point_frame_id: ""
    track_point_x: 0.0
    track_point_y: 0.0
    track_point_z: 0.0
